In [1]:
import numpy as np

In [5]:
#Créez à partir d’une liste un array unidimensionnel et 
#vérifiez sa taille et ce qu’il comporte.
arr1=np.array(range(5))
print arr1.dtype, arr1.shape

int32 (5L,)


In [7]:
#Créez un array bidimensionnel avec des valeurs quelconques, 
#calculer le cube de cet array

arr2=np.array([[1,4,7],[3,6,9]])
arr2**3


array([[  1,  64, 343],
       [ 27, 216, 729]])

In [10]:
#Générer un array avec des valeurs entre 0 et 8, 
#afficher les éléments 1 à 6 puis modifiez les éléments 6 à 8 
#en leur fixant la valeur de 22.
arr3=np.arange(9)
arr3[1:7]
arr3[6:9]=22
arr3

array([ 0,  1,  2,  3,  4,  5, 22, 22, 22])

In [12]:
#Construire une matrice rectangulaire de taille 3 x 2 avec une suite de nombres 
#commençant à 5, calculer le produit de la transposée par la matrice.
arr4=np.arange(5,11).reshape(3,2)
arr5=np.dot(arr4.T,arr4)
arr5

array([[155, 176],
       [176, 200]])

In [44]:
#Générer un array de nombres aléatoires puis remplacer les valeurs plus 
#petites que 0 par 0. Trier l’array obtenu
np.random.seed


In [49]:
arr6=np.random.randn(1000)
np.mean(arr6)

0.039842730498188615

In [50]:
arr6=np.where(arr6<0,0,arr6)
arr6

array([  0.00000000e+00,   0.00000000e+00,   2.20221572e-01,
         4.35682869e-01,   7.86797830e-01,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   7.07683268e-01,   0.00000000e+00,
         8.55435935e-01,   0.00000000e+00,   1.16390713e-01,
         0.00000000e+00,   0.00000000e+00,   8.28253730e-01,
         0.00000000e+00,   1.50036802e+00,   0.00000000e+00,
         8.74202404e-01,   0.00000000e+00,   1.69114541e+00,
         0.00000000e+00,   3.59654966e-01,   0.00000000e+00,
         8.57699195e-01,   7.96569095e-02,   0.00000000e+00,
         2.67191119e-01,   0.00000000e+00,   1.42870731e+00,
         0.00000000e+00,   1.10461300e-01,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   5.24721987e-01,
         4.47717073e-01,   0.00000000e+00,   1.27528416e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         1.35254695e+00,

In [52]:
#tri sur un array
arr7=np.sort(arr6)
arr6.sort()

In [56]:
#ecart-type de l'array
arr7.std()

0.59187846933000432

In [57]:
#génération d'un nombre aléatoire sur une loi normale et stockage dans un array
#1000 x 100
arr8=np.random.randn(100000).reshape(1000,100)

In [58]:
#exportation de l'array
np.save("array8.npy", arr8)
np.savetxt("array8.txt", arr8)