In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
import pandas as pd
import numpy as np

In [3]:
#importation des données
credit2=pd.ExcelFile("credit2.xlsx")
frameCredit2=credit2.parse()
frameCredit1=pd.read_table("credit1.txt")
frameCreditGlobal=pd.merge(frameCredit1,frameCredit2,how='left',on="Customer_ID")

In [6]:
#création de x et y pour le modèle
y=frameCreditGlobal["Accepted_Retention"]
col_pred=["Income","Age","RFM_Score","Average_Balance_Feed_Index"]
x=frameCreditGlobal[col_pred]

In [7]:
#création des échantillons d'apprentissage et de test
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [29]:
#création d'un objet random forest
modeleForest=RandomForestClassifier(5,max_depth=5)

In [26]:
#ajustement du modèle
modeleForest.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [19]:
#importance des variables
modeleForest.feature_importances_

array([ 0.49282192,  0.31013201,  0.07316289,  0.12388317])

In [27]:
#prediction à partir du modèle et de l'échantillon test
y_pred=modeleForest.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [28]:
#matrice de confusion
confusion_matrix(y_test,y_pred)

array([[529,   0],
       [ 71,   0]])

In [24]:
#matrice de confusion sur données d'apprentissage
y_pred2=modeleForest.predict(x_train)
confusion_matrix(y_train, y_pred2)

array([[1214,   10],
       [  50,  126]])